### PR TITLE
[WIP] Transactions

### PR DESCRIPTION
**Pull request by acburdine**
Refs #17

This is a work-in-progress on adding transactions support to the query builder

Tasks:
- [ ] Add initial transaction code
- [ ] Add tests
- [ ] Update readme

### CODE REVIEW

**Comment by acburdine** [comment]
@usmanhalalit the older travis build got stuck for some reason, would you mind stopping it?

**Comment by Mrhyuan** [comment]
it's better to support return false value to rollback the transactions

**Comment by acburdine** [comment]
@mrhyuan isn't the point of transactions to roll them back if there's a failure?

**Comment by Eragon666** [comment]
Any updates on the transactions, or a way I can use this on the master branch?

**Comment by acburdine** [comment]
@Eragon666 In theory transactions should work (I didn't test them before this was merged :confused: ). If you want to use them just require 'dev-master' in your `composer.json` file like so:

```json
{
    "require": {
       "usmanhalalit/pixie" : "dev-master"
    }
}
```

**Comment by Eragon666** [comment]
Thank you for the response. 

I checked the code for the transactions but it wasn't clear to me how to use it with Pixie. 

Can we also manually rollback a transaction, or is it only possible to rollback when PDO gives an exception? 

So for example: I add a new record (lets call it A) to the table, in another query I add items who depend on record A. But if for some reason no records are added (I check for duplicate keys), I want to rollback the changes for record A. 

How can I do that? Or isn't that possible yet with your transaction code?

**Comment by acburdine** [comment]
@Eragon666 those are good ideas :smile: I didn't get a chance to fully implement this but I'll see what I can do today.

**Comment by Eragon666** [comment]
@acburdine Please keep me updated :) If you don't have the time now, I can also take a closer look to this and see if I can implement it myself.

Also if you need any help, let me know!

**Comment by Eragon666** [comment]
@acburdine Hi! Any updates on the transactions?

**Comment by acburdine** [comment]
@Eragon666 sorry the last month or so got crazy with classes and such => should have some time to work on it tomorrow/this weekend. I'll let you know if I don't though.

**Comment by acburdine** [comment]
@Eragon666 see #102

**Comment by Eragon666** [comment]
@acburdine really nice. I will try it later this week! Thanks for your time!

**Pull request merged**
