### PR TITLE
Support array fetch mode

### PR DESCRIPTION
**Pull request by mayoz**
Return 0 when fetch mode is PDO::FETCH_ASSOC. Fixed it.

### CODE REVIEW

**Comment by neoascetic** [comment]
Could you please write a test so we can see where problem is?

**Comment by neoascetic** [comment]
Anyway, I think simpler and thus better solution is to force set `PDO::FETCH_OBJ` before fetching.

**Comment by mayoz** [comment]
No write test, maybe later.
Yes, you right but i think it should be merged. Some project need another fetch mode.

**Comment by neoascetic** [comment]
I meant we need to use `PDO::FETCH_OBJ` before fetching result of aggregation function, not any result. I. e. you are free to use any fetch mode, but aggregation method will use only `PDO::FETCH_OBJ` internally.

**Comment by mayoz** [comment]
Nonsense!

**Comment by usmanhalalit** [comment]
@mayoz,

Thanks for the PR, I appreciate you effort. But there are some better ways of doing it (on master), https://github.com/usmanhalalit/pixie/pull/16 .

Another thing, words like "Nonsense!" doesn't look good here. I am not sure if you're using Google Translator it made the word feel like so, but just saying.

**Pull request closed without merging**
