### PR TITLE
Fix PDO bindValue for bool

### PR DESCRIPTION
**Pull request by marc937**
When binding bool value, PHP casted true to '1' and false to '', so the query crased

### CODE REVIEW

**Comment by neoascetic** [comment]
I think it is better to use `PDO::PARAM_BOOL` in the case of boolean

**Comment by marc937** [comment]
PDO::PARAM_BOOL makes the query crashes silently. This is a known bug. They recommend to use PDO::PARAM_INT.

**Comment by usmanhalalit** [comment]
@marc937, can you please give some example queries?

**Comment by marc937** [comment]
Sorry for my late response. If you do an update using a boolean false value, the generated query will be wrong because casting a boolean to string in php gives us '1' and '' (empty string). For example, if I use

$data = array(
    'id' => 1,
    'valid' => false
);
QB::table('test')->insert($data);

The query will crash because the generated SQL will be

INSERT INTO test (id, valid) VALUES (1, '')

This is why I modified the line 146 of the file src/Pixie/QueryBuilder/QueryBuilderHandler.php. Casting a boolean to int gives us 1 and 0, which is good to MySQL because the "boolean" type in MySQL is TINYINT(1). I tried PDO::PARAM_BOOL too, but as I said, the query crashes without any error. After a few Google searches, I found that PDO::PARAM_BOOL is a known PDO issue. That's why I'm using PDO::PARAM_INT.

**Comment by neoascetic** [comment]
LGTM

**Comment by marc937** [comment]
Should I do another pull request?

**Comment by usmanhalalit** [comment]
Done :)

**Comment by marc937** [comment]
By the way, thanks for that nice lib

**Pull request merged**
