### PR TITLE
Feature: no table support

### PR DESCRIPTION
**Pull request by skipperbent**
Added support for not defining any table (so calling `QueryBuilderHandler()->table()` is no longer required).

Can be useful for situations where you are using multiple subqueries to generate the rows without doing a specific query to any tables.

**SQL Example:**

``` sql
SELECT (SELECT COUNT(*) FROM `mail`) as mail_count, (SELECT COUNT(*) FROM `event_message`) as message_count
```

**Pixie example:**

``` php
$subQuery1 = $this->builder->table('mail')->select($this->builder->raw('COUNT(*)'));
$subQuery2 = $this->builder->table('event_message')->select($this->builder->raw('COUNT(*)'));

$count = $this->builder->select($this->builder->subQuery($subQuery1, 'row1'), $this->builder->subQuery($subQuery2, 'row2'))->first();
```

I've created tests for this, which can be found in the `NoTableSubQueryTest` test-class.

### CODE REVIEW

**Comment by TCB13** [comment]
This is useful :)

**Comment by skipperbent** [comment]
I've added this and multiple other useful features in my custom fork, available here:

https://github.com/skipperbent/pecee-pixie

**Comment by TCB13** [comment]
@skipperbent maybe you should PR all your changes to this project. The maintainer of this one had some heath complications lately but he is back.

**Comment by TCB13** [comment]
@usmanhalalit please merge!

**Pull request merged**
