### PR TITLE
Bugfix where false bool

### PR DESCRIPTION
**Pull request by skipperbent**
Fixed error on PHP 5.6.10 - not sure if other versions are affected.

**Query:**

``` php
$result = $this->builder->table('test')->where('deleted', '=', false);
```

**Causes invalid query:**

``` sql
SELECT * FROM `cb_test` WHERE `deleted` =  // no quotation marks or int-replacement here
```

Tests added: `QueryBuilderTest` -> `testFalseBoolWhere()`

### CODE REVIEW

**Comment by eL-Prova** [comment]
Why should you ever check an id by bool?

**Comment by skipperbent** [comment]
You're missing the point... The column name is irrelevant :)

**Comment by eL-Prova** [comment]
After this commit I understand your problem. I should never have used the bool but use the int value itself. But can be usefull maybe :-)

**Comment by skipperbent** [comment]
@eL-Prova 

Great haha but I changed the column names like you suggested - don't know why i chose `id` as the name, I can understand your confusion haha :) 

I've also first noticed the error recently as it seems like `true` will be considered an int - but `false` will not and cause and empty value instead (without quotes or integer values).

**Comment by mikegioia** [comment]
Is it possible to merge this to 2.x?

**Comment by skipperbent** [comment]
@mikegioia 

I've created a new standalone fork of Pixie as this maintainer doesn't seem to have the time to look at pull requests any longer.

The above fix plus many other fixes and optimisations are included in my version.

**Comment by eL-Prova** [comment]
@skipperbent @mikegioia my version is almost up-to-date. I had only extend the functions for easy create/update/delete columns and tables. Maybe good to have one place and make one or two people also  owner so we can maintain the repo with more people.

**Comment by TCB13** [comment]
I usually go with bools all the time and never had this issue.

**Comment by FinesseRus** [comment]
IMHO, casting boolean to integer must be done while [binding](https://github.com/usmanhalalit/pixie/blob/master/src/Pixie/QueryBuilder/QueryBuilderHandler.php#L146) and [making raw SQL](https://github.com/usmanhalalit/pixie/blob/master/src/Pixie/QueryBuilder/QueryObject.php#L66), not while collecting wheres. `QueryBuilderHandler` only collects data, it doesn't build SQL, therefore it must be value agnostic.

Boolean values are already considered while binding but not considered while making raw SQL (boolean is casted to string, PHP casts `false` to empty string).

**Comment by FinesseRus** [comment]
The using of the method `getRawSql` is a great error in Pixie. Inserting values to SQL query text avoiding binding causes many problems:

* Statements can't be cached by DB server because the SQL text is always different.
* Debug output and the real SQL differ which causes problems like this: https://github.com/usmanhalalit/pixie/pull/141#issuecomment-337034154.
* Incorrect value-to-SQL conversion causes bugs (for example https://github.com/usmanhalalit/pixie/pull/141, https://github.com/usmanhalalit/pixie/issues/166).

**Comment by usmanhalalit** [comment]
I couldn't produce the error. @eL-Prova @TCB13 if you folks faced it then please let me know.

**Pull request closed without merging**
