### PR TITLE
Adding options for mutate tables and columns

### PR DESCRIPTION
**Pull request by eL-Prova**
Make it possible to create queries for mutating the table. In my case
used for migrations.

Options for tables: Create / Alter / Rename / Drop tables
Options for columns: Create / Alter / Rename / Drop columns

### CODE REVIEW

**Comment by TCB13** [comment]
@eL-Prova I would really like to have this in my code, also for migrations :) but haven't test it yet. Can you add some documentation? Thanks.

**Comment by eL-Prova** [comment]
@TCB13 yes I have multiple examples. I will try to create some documentation but it should first be merged back.

**Comment by TCB13** [comment]
@usmanhalalit what's your opinion this features and the `$this->builder...` syntax?

**Comment by usmanhalalit** [comment]
Thanks @eL-Prova, but this seems like a massive change to me which I'm unable to manage at this moment. That's my problem though.

**Comment by TCB13** [comment]
The latest tests were a success, it is a very good start.

**Pull request closed without merging**
